### ISSUE TITLE
[BUG] cypress-diff crashes cypress

### ISSUE THREAD

**Issue by YeonV** [elaichenkov/cypress-diff#17]
1. Thank you soo much for this wonderful project. This should be included in cypress, because it is soo nice!
2. When implementing this, im getting the following error:

<details>
<summary>Click to expand</summary>

![image](https://github.com/elaichenkov/cypress-diff/assets/28861537/55fde4f1-4bbe-4995-bd16-efb74d1ec6a6)

</details>

3. from package.json:
"cypress": "12.17.0"
"cypress-diff": "^0.0.5",
"cypress-fs": "^0.2.4",
"cypress-iframe": "^1.0.1",

4. node versions tested:
18 & 20

5. tested on both: chrome & electron:
![image](https://github.com/elaichenkov/cypress-diff/assets/28861537/0ed26021-2efa-4369-9802-c5783572896f)

Any help would be appreciated <3
Thx
Blade (aka YeonV)

**Comment by elaichenkov** [comment]
Hey @YeonV ,

Thank you! It seems like a preprocessor issue. Do you use any? Would you mind sharing your config file and `e2e.js`? Moreover, please create a minimal reproducible example/repo.

**Comment by YeonV** [comment]
@elaichenkov Thank you soo much for answering me,

of course i can provide anything you need.

config:
```js
import { defineConfig } from 'cypress'
import yzfs from './node_modules/cypress-fs/plugins/index.js'

export default defineConfig({
    viewportWidth: 1000,
    viewportHeight: 2000,
    projectId: 'XXXXXX',
    video: false,

    e2e: {
        chromeWebSecurity: false,
        testIsolation: false,
        setupNodeEvents(on, config) {
            // implement node event listeners here
            (yzfs as any)(on, config)
        }
    },
    component: {
        devServer: {
            framework: 'next',
            bundler: 'webpack'
        }
    }
})
```

e2e.ts:
```ts
// ***********************************************************
// This example support/e2e.ts is processed and
// loaded automatically before your test files.
//
// This is a great place to put global configuration and
// behavior that modifies Cypress.
//
// You can change the location of this file or turn off
// automatically serving support files with the
// 'supportFile' configuration option.
//
// You can read more here:
// https://on.cypress.io/configuration
// ***********************************************************

// Import commands.js using ES2015 syntax:
import './commands'

// Alternatively you can use CommonJS syntax:
// require('./commands')

import 'cypress-fs'
import 'cypress-diff'
```

sadly i cannot create a minimal reproduction example that fast, but i will provide as soon as possible.
(just thought, maybe those 2 files can already help a bit)

**Comment by elaichenkov** [comment]
No problem. It's really awesome that it works now.
