### ISSUE TITLE
The plugin is not working on our side. 

### ISSUE THREAD

**Issue by estefafdez** [elaichenkov/cypress-diff#6]
Hey, @elaichenkov! 

First of all, thank you very much for this plugin and the incredible idea! 

We have a huge cypress project and it will be really useful to us to have a plugin like this installed and working. We are using TS + Cypress 13.6.0 version. 

We followed your exact instructions from the readme, including the optional part but still, we can not see the plugin working with the: 

```
- .should('have.text') method. 
- .should('have.value') method. 
- .contains(...) method. 
```

and it's not working on our side. Also, we notice that you suggest adding the import on the `support/index.ts` file when it should be on the `support/e2e.ts` file (since cypress 10 I think if I recall correctly). 

Could you please have a look? 

Thanks again for your invaluable effort!

**Comment by elaichenkov** [comment]
Hey @estefafdez 

Thank you for trying the library. That's my bad, it should be in the `support/e2e.js`. I've updated the documentation. However, it's not working for `contains` anyway. Meanwhile, it should work with `have.text` and `have.value`. Can you please provide a minimal reproducible example so I can help you? or maybe content of the `support/e2e.js` file

**Comment by estefafdez** [comment]
True, that's something on us, and on the pre-processor we have to handle the tests (webpack). I will investigate and let you know but it's working as expected on a simple repo (https://github.com/UnaQAEnApuros/cypress-template/pull/93). 

Thanks!
